### ISSUE TITLE
Dinero Viaje 

### ISSUE THREAD

**Issue by nicolassplanass** [nicolassplanass/Ejercicio-2-#1]
### DINERO A GASTAR 

1. Es necesario saber de cuanto dinero dispone cada persona para saber el limite de destino, alojamientos y transporte que esto llevaría a cabo.
2. También es imprescindible saber si comeremos fuera o en el Airbnb ( apartamento turístico ), para poder organizar el dinero y los días en cada destino.
Por ello, podemos hacer un excel compartido para saber los gastos individiales, comunes y totales y ponernos de acuerdo con los destinos.

**Comment by nicolassplanass** [comment]
que os parece

**Comment by ctz1002** [comment]
Genial, ademas podriamos usar a app 'tricount ' que sirve para saber cuanto dinero ponemos y debemos cada integrante
