### ISSUE TITLE
Destinos

### ISSUE THREAD

**Issue by nicolassplanass** [nicolassplanass/Ejercicio-2-#2]
Una vez acabado el tema del dinero, es necesario los destinos necesarios para ir por Europa.
Todo ello conlleva ponernos de acuerdo para luego buscar alojamiento adecuado y los medios de transporte correspondientes.
**_De momento, tenemos estas páginas para poder realizar nuestras rutas_** 

1. https://www.eurail.com/en/plan-your-trip/
2. https://www.skyscanner.es/
3. https://www.civitatis.com/

**Comment by ctz1002** [comment]
Creo que una pagina para coger autobuses puede ser necesaria para movernos entre las ciudades.
          4. https://www.alsa.es/

**Comment by nicolassplanass** [comment]
y https://www.flixbus.es/
