### ISSUE TITLE
Transporte

### ISSUE THREAD

**Issue by nicolassplanass** [nicolassplanass/Ejercicio-2-#3]
### **Elegir** entre :

-  Avión en ida y vuelta y trenes para moverse por Europa
- Todo el viaje en avión
- Todo el viaje en tren
- Alquiler de coches
**Tenemos distintas páginas para comparar:**
Forocoches
Eurotrip

**Comment by ctz1002** [comment]
voy a añadir alguna mas que seguro que nos sirven de ayuda
    https://ryanair.com
    https://www.trenes.com
