### ISSUE TITLE
Alojamientos

### ISSUE THREAD

**Issue by nicolassplanass** [nicolassplanass/Ejercicio-2-#6]
### **Webs de Hoteles/Apartamentos:**
- https://www.airbnb.es/
- https://www.booking.com/
- https://www.trivago.es/

**Comment by ctz1002** [comment]
Creo que lo mas sencillo puede ser coger un apartamento en vez de un hotel, asi  tenemos mas libertad a la hora de la comida.

**Comment by nicolassplanass** [comment]
yo también opino lo mismo

**Comment by MilagrosVarelaSan** [comment]
Pienso lo mismo, incluso los apartamentos nos permite mantenernos en nuestro espacio, nos ofrece más seguridad y son más económicos que los hoteles.
