### ISSUE TITLE
Investigación del Destino

### ISSUE THREAD

**Issue by nicolassplanass** [nicolassplanass/Ejercicio-2-#7]
Ver el idioma, moneda, transporte por la ciudad y características del destino.
Saber el tiempo y temperatura para poder organizar las maletas y ropa adecuada para el destino.
También saber los barrios turísticos y peligrosos, para evitar robos

**Comment by ctz1002** [comment]
Deberíamos tener tambien en cuenta a que hora empieza y acaba el transporte publico de cada ciudad para poder organizarnos y llegar al alojamiento sin problema.

**Comment by nicolassplanass** [comment]
pues con la app de moovit se podría
